USE CuahangNongDuoc;
GO

-- 1. Đơn vị tính
CREATE TABLE DON_VI_TINH (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TEN_DON_VI NVARCHAR(50) NOT NULL
);

-- 2. Nhà cung cấp
CREATE TABLE NHA_CUNG_CAP (
    ID VARCHAR(20) PRIMARY KEY,
    HO_TEN NVARCHAR(100) NOT NULL,
    DIA_CHI NVARCHAR(200),
    DIEN_THOAI VARCHAR(20)
);

-- 3. Đại lý
CREATE TABLE DAI_LY (
    ID VARCHAR(20) PRIMARY KEY,
    DAI_LY NVARCHAR(100) NOT NULL,
    DIA_CHI NVARCHAR(200),
    DIEN_THOAI VARCHAR(20)
);

-- 4. Khách hàng
CREATE TABLE KHACH_HANG (
    ID VARCHAR(20) PRIMARY KEY,
    HO_TEN NVARCHAR(100) NOT NULL,
    DIA_CHI NVARCHAR(200),
    DIEN_THOAI VARCHAR(20),
    LOAI_KH INT DEFAULT 0  -- 0: khách lẻ, 1: đại lý
);

-- 5. Lý do chi
CREATE TABLE LY_DO_CHI (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    LY_DO NVARCHAR(100) NOT NULL
);

-- 6. Sản phẩm
CREATE TABLE SAN_PHAM (
    ID VARCHAR(20) PRIMARY KEY,
    TEN_SAN_PHAM NVARCHAR(200) NOT NULL,
    SO_LUONG INT DEFAULT 0,
    DON_GIA_NHAP DECIMAL(18,0) DEFAULT 0,
    GIA_BAN_SI DECIMAL(18,0) DEFAULT 0,
    GIA_BAN_LE DECIMAL(18,0) DEFAULT 0,
    ID_DON_VI_TINH INT FOREIGN KEY REFERENCES DON_VI_TINH(ID)
);

-- 7. Phiếu nhập
CREATE TABLE PHIEU_NHAP (
    ID VARCHAR(20) PRIMARY KEY,
    NGAY_NHAP DATETIME DEFAULT GETDATE(),
    TONG_TIEN DECIMAL(18,0) DEFAULT 0,
    DA_TRA DECIMAL(18,0) DEFAULT 0,
    CON_NO DECIMAL(18,0) DEFAULT 0,
    ID_NHA_CUNG_CAP VARCHAR(20) FOREIGN KEY REFERENCES NHA_CUNG_CAP(ID)
);

-- 8. Mã sản phẩm (lô hàng)
CREATE TABLE MA_SAN_PHAM (
    ID VARCHAR(30) PRIMARY KEY,
    ID_SAN_PHAM VARCHAR(20) FOREIGN KEY REFERENCES SAN_PHAM(ID),
    ID_PHIEU_NHAP VARCHAR(20) FOREIGN KEY REFERENCES PHIEU_NHAP(ID),
    DON_GIA_NHAP DECIMAL(18,0),
    SO_LUONG INT DEFAULT 0,
    NGAY_NHAP DATETIME,
    NGAY_SAN_XUAT DATETIME,
    NGAY_HET_HAN DATETIME
);

-- 9. Phiếu bán
CREATE TABLE PHIEU_BAN (
    ID VARCHAR(20) PRIMARY KEY,
    ID_KHACH_HANG VARCHAR(20) FOREIGN KEY REFERENCES KHACH_HANG(ID),
    NGAY_BAN DATETIME DEFAULT GETDATE(),
    TONG_TIEN DECIMAL(18,0) DEFAULT 0,
    DA_TRA DECIMAL(18,0) DEFAULT 0,
    CON_NO DECIMAL(18,0) DEFAULT 0
);

-- 10. Chi tiết phiếu bán
CREATE TABLE CHI_TIET_PHIEU_BAN (
    ID_PHIEU_BAN VARCHAR(20) FOREIGN KEY REFERENCES PHIEU_BAN(ID),
    ID_MA_SAN_PHAM VARCHAR(30) FOREIGN KEY REFERENCES MA_SAN_PHAM(ID),
    SO_LUONG INT,
    DON_GIA DECIMAL(18,0),
    THANH_TIEN DECIMAL(18,0),
    PRIMARY KEY (ID_PHIEU_BAN, ID_MA_SAN_PHAM)
);

-- 11. Phiếu thanh toán (Phiếu thu)
CREATE TABLE PHIEU_THANH_TOAN (
    ID VARCHAR(20) PRIMARY KEY,
    NGAY_THANH_TOAN DATETIME DEFAULT GETDATE(),
    TONG_TIEN DECIMAL(18,0),
    ID_KHACH_HANG VARCHAR(20) FOREIGN KEY REFERENCES KHACH_HANG(ID),
    GHI_CHU NVARCHAR(200)
);

-- 12. Phiếu chi
CREATE TABLE PHIEU_CHI (
    ID VARCHAR(20) PRIMARY KEY,
    NGAY_CHI DATETIME DEFAULT GETDATE(),
    TONG_TIEN DECIMAL(18,0),
    ID_LY_DO_CHI INT FOREIGN KEY REFERENCES LY_DO_CHI(ID),
    GHI_CHU NVARCHAR(200)
);

-- 13. Dư nợ khách hàng
CREATE TABLE DU_NO_KH (
    ID_KHACH_HANG VARCHAR(20) FOREIGN KEY REFERENCES KHACH_HANG(ID),
    THANG INT,
    NAM INT,
    DAU_KY DECIMAL(18,0) DEFAULT 0,
    PHAT_SINH DECIMAL(18,0) DEFAULT 0,
    DA_TRA DECIMAL(18,0) DEFAULT 0,
    CUOI_KY DECIMAL(18,0) DEFAULT 0,
    PRIMARY KEY (ID_KHACH_HANG, THANG, NAM)
);

-- 14. Tham số hệ thống
CREATE TABLE THAM_SO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    PHIEU_BAN INT DEFAULT 0,
    NHA_CUNG_CAP INT DEFAULT 0,
    KHACH_HANG INT DEFAULT 0,
    PHIEU_NHAP INT DEFAULT 0,
    PHIEU_THANH_TOAN INT DEFAULT 0,
    TEN_CUA_HANG NVARCHAR(100),
    DIA_CHI NVARCHAR(200),
    DIEN_THOAI VARCHAR(20),
    SAN_PHAM INT DEFAULT 0,
    PHIEU_CHI INT DEFAULT 0
);
CREATE TABLE VAI_TRO (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TEN_VAI_TRO NVARCHAR(50) NOT NULL,
    MO_TA NVARCHAR(200)
);
GO

CREATE TABLE NGUOI_DUNG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TEN_DANG_NHAP VARCHAR(50) NOT NULL UNIQUE,
    MAT_KHAU VARCHAR(100) NOT NULL,
    HO_TEN NVARCHAR(100) NOT NULL,
    ID_VAI_TRO INT NOT NULL FOREIGN KEY REFERENCES VAI_TRO(ID),
    TRANG_THAI BIT DEFAULT 1,
    NGAY_TAO DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO VAI_TRO (TEN_VAI_TRO, MO_TA) VALUES
(N'Admin', N'Quản trị viên'),
(N'Nhân viên Bán hàng', N'Bán hàng'),
(N'Nhân viên Kho', N'Quản lý kho'),
(N'Kế toán', N'Kế toán');
GO

INSERT INTO NGUOI_DUNG (TEN_DANG_NHAP, MAT_KHAU, HO_TEN, ID_VAI_TRO) VALUES
('admin', '123', N'Nguyễn Văn Admin', 1),
('banhang', '123', N'Trần Thị Bán Hàng', 2),
('kho', '123', N'Lê Văn Kho', 3),
('ketoan', '123', N'Phạm Thị Kế Toán', 4);
GO
SELECT * FROM VAI_TRO;
SELECT * FROM NGUOI_DUNG;